name: Deploy MkDocs to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build MkDocs Site
      run: |
        mkdocs build

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: eduwecloudlabs  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './site'
